dnd-side-project/dnd-11th-7-backend

src/main/java/com/dnd/zzaekkac/ZzaekkacApplication.java
src/main/java/com/dnd/zzaekkac/domain/example/controller/ExampleController.java
src/main/java/com/dnd/zzaekkac/domain/example/dto/request/ExampleCreateRequestDto.java
src/main/java/com/dnd/zzaekkac/domain/example/dto/request/ExampleUpdateRequestDto.java
src/main/java/com/dnd/zzaekkac/domain/example/dto/response/ExampleResponse.java
src/main/java/com/dnd/zzaekkac/domain/example/entity/Example.java
src/main/java/com/dnd/zzaekkac/domain/example/exception/ExampleAlreadyExistsException.java
src/main/java/com/dnd/zzaekkac/domain/example/exception/ExampleNotFoundException.java
src/main/java/com/dnd/zzaekkac/domain/example/repository/ExampleRepository.java
src/main/java/com/dnd/zzaekkac/domain/example/service/ExampleService.java
src/main/java/com/dnd/zzaekkac/global/config/security/SecurityConfig.java
src/main/java/com/dnd/zzaekkac/global/exception/ErrorResponse.java
src/main/java/com/dnd/zzaekkac/global/exception/ExceptionController.java
src/main/java/com/dnd/zzaekkac/global/exception/GeneralException.java
src/main/resources/application.properties
src/test/java/com/dnd/zzaekkac/ZzaekkacApplicationTests.java

#3 
- 패키지명 수정
- 의논했던 General Exception 처리

Feature/#3 서비스명 변경에 따른 패키지 구조 수정

---

.github/workflows/deploy.yml
Dockerfile
src/main/java/com/dnd/zzaekkac/domain/example/controller/ExampleController.java
src/main/java/com/dnd/zzaekkac/domain/example/controller/MainController.java

#5 
- AWS EC2, ECR 연결
- Github Actions 구성
- Dockerfile

Feature/#5 배포

---

build.gradle
src/docs/asciidoc/api/category.adoc
src/docs/asciidoc/index.adoc
src/main/java/com/dnd/zzaekkac/domain/category/controller/CategoryController.java
src/main/java/com/dnd/zzaekkac/domain/category/dto/response/CategoryResponseDto.java
src/main/java/com/dnd/zzaekkac/domain/category/entity/Category.java
src/main/java/com/dnd/zzaekkac/domain/category/exception/CategoryNotFoundException.java
src/main/java/com/dnd/zzaekkac/domain/category/repository/CategoryRepository.java
src/main/java/com/dnd/zzaekkac/domain/category/repository/CategoryRepositoryCustom.java
src/main/java/com/dnd/zzaekkac/domain/category/repository/CategoryRepositoryImpl.java
src/main/java/com/dnd/zzaekkac/domain/category/service/CategoryService.java
src/test/java/com/dnd/zzaekkac/domain/category/controller/CategoryControllerTest.java

#20 
ERD에서 설계한 내용을 바탕으로 Entity Mapping을 진행하였습니다.
또한, 카테고리의 경우 DB에 값을 넣은 후 변동이 없는 점을 고려하여 별도의 생성/수정/삭제(CUD) 작업은 진행하지 않았습니다.
Spring REST Docs를 도입하였습니다. 제가 작성한 테스트 코드를 참고해서 함께 작성해주세요!

Feature/#20 카테고리 

---

.gitignore
src/main/resources/static/index.html

배포 환경에서 Spring REST Docs가 보이도록 구성합니다.

DEPLOY / Spring REST Docs 페이지 추가

---

src/test/java/com/dnd/jjakkak/JjakkakApplicationTests.java
src/test/java/com/dnd/jjakkak/domain/category/repository/CategoryRepositoryTest.java
src/test/java/com/dnd/jjakkak/domain/category/service/CategoryServiceTest.java

#20 
카테고리에 관한 테스트 (Controller, Service, Repository)를 진행하였습니다.

Feature/#20 카테고리 테스트 추가

---

build.gradle
src/docs/asciidoc/api/meeting.adoc
src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java
src/test/java/com/dnd/jjakkak/config/JjakkakMockSecurityContext.java
src/test/java/com/dnd/jjakkak/config/JjakkakMockUser.java
src/test/java/com/dnd/jjakkak/config/RestDocsConfiguration.java
src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java

#43 
- Controller에서 **SecurityContextHolder** 를 통해 회원의 정보 가져오는 방식으로 변경
- 테스트 코드를 모두 단위 테스트로 변경
Controller도 통합 테스트가 아닌 단위 테스트로 진행하다보니 변경사항이 있습니다.
해당 내용은 스크럼 후에 개별적으로 알려드릴게요! (문서로도 작성해서 Discussion에 올리도록 하겠습니다 👀)

Refactor/#43 모임 

---

src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java
src/test/java/com/dnd/jjakkak/domain/category/CategoryDummy.java
src/test/java/com/dnd/jjakkak/domain/category/controller/CategoryControllerTest.java
src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java

#48 
카테고리의 컨트롤러 테스트를 수정하였습니다.
- Controller Layer unit test 진행
- CategoryDummy Class 추가하여 static method를 통해 더미 데이터 반환

Feature/#48 카테고리 테스트 코드 수정

---

src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java

JwtFilter에 존재하는 로그 삭제 후 재배포 진행 ..

Deploy/로그 삭제 후 재배포 

---

src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java

CORS 설정 후 재배포 
- 포트번호 변경
- 허용 메서드 수정 (* -> GET, POST, PUT, DELETE, PATCH, OPTIONS로 직접 명시)

Deploy/cors 설정

---

src/main/java/com/dnd/jjakkak/JjakkakApplication.java
src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2FailureHandler.java
src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
src/main/java/com/dnd/jjakkak/domain/jwt/provider/JwtProvider.java
src/main/java/com/dnd/jjakkak/global/config/proprties/JjakkakProperties.java
src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java

Deploy/redirect URL 수정

---

src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java

응답 쿠키 (RT)에 same site 설정 후 재배포

Deploy/쿠키 samesite 설정

---

src/main/resources/static/index.html
src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java

#89 
**변경 전**
**변경 후**
기존 `request param` 으로 넘어가던 csrf를 헤더 요청으로 변경하였습니다.
X

Refactor/#89 CSRF 수정 (MockMVC)

---

src/main/java/com/dnd/jjakkak/global/exception/ExceptionController.java

Resolves #92 
서버 에러 응답 수정
- 로깅 추가 (log.error)
- 클라이언트에 메시지를 바로 넘기는 것은 보안상 위험하여 수정

[Refactor] 서버 에러 처리 수정

---

src/main/java/com/dnd/jjakkak/domain/dateofschedule/service/DateOfScheduleService.java

resolves #95 
회의 내용에서 정리한 우선순위를 안보내는 방식에 대응하도록 고정 값으로 지정

[Refactor] 모임 일정의 우선 순위 (rank) 고정

---

src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingTime.java
src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingTimeResponseDto.java
src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
src/main/resources/static/index.html
src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
src/test/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryTest.java
src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java

resolves #102, #103 
- 모임(Meeting) API 수정 
- 모임 일정 조회 응답 수정 - 총 인원, 익명 여부 추가
- 모임 정보 조회 오류 수정 - 카테고리가 여러개 나오는 현상
- JWT Filter 검증 수정 (#103)
- 모임 일정(Schedule) API 수정
- 회원/비회원 할당시 익명일 경우, 프론트 측에서 값을 넘겨주지 않아 `nullable` 허용 후 체크
생각보다 변경사항이 많아졌네요,, ㅋㅋㅋㅋㅋㅋ 양해 부탁드려요!!

[Refactor] 모임 관련 리팩토링 및 오류 수정

---

src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2FailureHandler.java
src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
src/main/java/com/dnd/jjakkak/global/config/security/CustomAuthorizationRequestResolver.java
src/main/java/com/dnd/jjakkak/global/config/security/FailedAuthenticationEntryPoint.java
src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java

resolves #105 
- OAuth2AuthorizationRequestResolver 커스터마이징 적용 (SecurityConfig)
- OAuth2SuccessHandler 수정
- OAuth2FailureHandler 수정
저도 잘 모르는 내용이니 나중에 한 번 Discussion에 내용 정리해볼게여

[Refactor] 로그인 후 리다이렉트 URL 수정 

---

src/main/java/com/dnd/jjakkak/domain/dateofschedule/repository/DateOfScheduleRepository.java
src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java

resolves #110 
이슈 내용과 동일하게 작업하였습니다. 
x

[Fix] 일정 수정 관련 버그 수정

---

src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
src/main/java/com/dnd/jjakkak/domain/schedule/dto/request/ScheduleUpdateRequestDto.java
src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
src/main/resources/static/index.html
src/test/java/com/dnd/jjakkak/domain/schedule/ScheduleDummy.java
src/test/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleControllerTest.java
src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java

resolves #112 
- 회원 일정 수정 API 구현 
- 일정 테스트 코드 수정
x

[Feature] 회원 일정 수정 API 

---

src/main/java/com/dnd/jjakkak/domain/dateofschedule/dto/response/DateOfScheduleResponseDto.java
src/main/java/com/dnd/jjakkak/domain/schedule/dto/response/ScheduleResponseDto.java
src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryCustom.java
src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryImpl.java
src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
src/main/resources/static/index.html
src/test/java/com/dnd/jjakkak/domain/schedule/ScheduleDummy.java
src/test/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleControllerTest.java
src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java

resolves #114 
**위의 이슈 참고**
_기존 API 응답 값_
_변경된 API 응답 값_
x

[Refactor] 일정 조회 수정 (회원/비회원)

---

src/main/java/com/dnd/jjakkak/domain/meeting/exception/MeetingAlreadyEndedException.java
src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
src/test/java/com/dnd/jjakkak/domain/schedule/ScheduleDummy.java
src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java

resolves #116 
로직에서 처리해야 할 내용들을 빼고 작성하여 수정하였습니다.
현재 시간을 기준으로, 일정 마감 시간(DueDateTime)과 비교하여 이미 기간이 지난 이후라면,
- 새로운 일정을 할당
- 기존 일정을 수정
위의 두 작업시 예외가 발생하도록 조치하였습니다.

[Refactor] 모임의 일정 마감 시간 적용

---

src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java

resolves #133 
화이트 리스트인 경우, 필터를 타지 않도록 `shouldNotFilter` 메서드를 재정의하였습니다.
X

[Feat] JWT 필터 권한 체크 로직 수정

---

src/main/java/com/dnd/jjakkak/domain/dateofschedule/service/DateOfScheduleService.java
src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java

resolves #142 
회원/비회원의 일정 수정시, 일정 날짜 (DateOfSchedule)이 잘못 저장되는 버그를 수정하였습니다.
x

[Fix] 일정 수정 오류 

---

src/main/java/com/dnd/jjakkak/domain/jwt/provider/JwtProvider.java
src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
src/main/java/com/dnd/jjakkak/domain/member/dto/response/AccessTokenResponseDto.java

resvoles #154 
issue 내용과 동일 
x

[FEAT] 토큰(Access Token) 재발급 응답 수정 

---

src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingCreateRequestDto.java

resolves #160 
- "dueDateTime": "2024-12-10T23:59:59"
- "meetingStartDate": "2024-12-10" 
위와 같이 설정되어있을 경우, 모임이 생성되지 않는 문제를 해결하기 위해서 검증 부분을 수정하였습니다.

[Fix] 모임 - 일정 입력 마감 기한 검증 수정
